DECLARE
    L_COUNT NUMBER;
    L_COLUMNS_VALUES VARCHAR2(1000);
    L_KEY_COLUMN VARCHAR2(25);
    L_Process Number;
    BEGIN
    SELECT COUNT(*) INTO L_COUNT  FROM (
    SELECT * FROM (SELECT ID,NAME,DESIGNATION,SALARY FROM Source_A
    MINUS
    SELECT ID,NAME,DESIGNATION,SALARY FROM Source_B)
    UNION ALL
    SELECT * FROM (SELECT ID,NAME,DESIGNATION,SALARY FROM Source_B
    MINUS
    SELECT ID,NAME,DESIGNATION,SALARY FROM Source_A)
    );
    
        DBMS_OUTPUT.PUT_LINE(L_COUNT);
        IF L_COUNT<>0 THEN
        L_COLUMNS_VALUES:='';
            FOR I IN (
            SELECT COLUMN_NAME FROM USER_TAB_COLS WHERE TABLE_NAME='SOURCE_A'
            INTERSECT
            SELECT COLUMN_NAME FROM USER_TAB_COLS WHERE TABLE_NAME='SOURCE_B') LOOP
        
        L_COLUMNS_VALUES:=L_COLUMNS_VALUES||I.COLUMN_NAME||'~';
        END LOOP;
        
        END IF;        
        
        L_COLUMNS_VALUES:=SUBSTR(L_COLUMNS_VALUES,1,LENGTH(L_COLUMNS_VALUES)-1);
        DBMS_OUTPUT.PUT_LINE(L_COLUMNS_VALUES);
        BEGIN
            BEGIN
            SELECT COLUMN_NAME INTO L_KEY_COLUMN FROM (SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE TABLE_NAME='SOURCE_A'
            INTERSECT
            SELECT COLUMN_NAME FROM ALL_CONS_COLUMNS WHERE TABLE_NAME='SOURCE_B');
            DBMS_OUTPUT.PUT_LINE(L_KEY_COLUMN); 
            INSERT INTO TM_MISMATCH_Maint VALUES(SQ_PROCESS.NEXTVAL,'Source_A','Source_B',L_KEY_COLUMN,'Y');
            END;
                       
        FOR I IN ( SELECT REGEXP_SUBSTR(L_COLUMNS_VALUES,'[^~,]+', 1, LEVEL) KEY_COM
        FROM DUAL CONNECT BY REGEXP_SUBSTR(L_COLUMNS_VALUES,'[^~,]+', 1, LEVEL) IS NOT NULL) LOOP
        DBMS_OUTPUT.PUT_LINE(I.KEY_COM);
        INSERT INTO TM_MISMATCH_Maint_Sub VALUES('Source_A',I.KEY_COM,'Source_A',I.KEY_COM,'Y','Y');
        END LOOP;
        END;
        --INSERT INTO TM_MISMATCH_Maint VALUES(SQ_PROCESS.NEXTVAL,'Source_A','Source_B',L_COLUMNS_VALUES,'Y');
        BEGIN        
        FOR I IN ( SELECT REGEXP_SUBSTR(L_COLUMNS_VALUES,'[^~,]+', 1, LEVEL) KEY_COM
        FROM DUAL CONNECT BY REGEXP_SUBSTR(L_COLUMNS_VALUES,'[^~,]+', 1, LEVEL) IS NOT NULL) LOOP
        DBMS_OUTPUT.PUT_LINE(I.KEY_COM);
        --INSERT INTO TM_MISMATCH_Maint_Sub VALUES('Source_A',I.KEY_COM,'Source_A',I.KEY_COM,'Y','Y');
        END LOOP;
        END;
        
        BEGIN
        FOR KEY IN (
            SELECT ID FROM (
            SELECT * FROM (SELECT ID,NAME,DESIGNATION,SALARY FROM Source_A
            MINUS
            SELECT ID,NAME,DESIGNATION,SALARY FROM Source_B)
        UNION ALL
            SELECT * FROM (SELECT ID,NAME,DESIGNATION,SALARY FROM Source_B
            MINUS
            SELECT ID,NAME,DESIGNATION,SALARY FROM Source_A)
    ) )LOOP
    SELECT Process_No into L_Process FROM TM_MISMATCH_Maint WHERE Source_Table='Source_A' and Target_Table='Source_B';
    DBMS_OUTPUT.PUT_LINE(KEY.ID||
    '  '||
    L_Process||
    L_KEY_COLUMN||'  '||
    KEY.ID||'  '||
    NULL
    );
    /*INSERT INTO TL_Mismatch_Key_Details VALUES (SYSDATE,
    (SELECT Process_No FROM TM_MISMATCH_Maint WHERE Source_Table='Source_A' and Target_Table='Source_B'),
    L_KEY_COLUMN,KEY.ID,NULL);
    */
    END LOOP;
        END;
  
    END;
    /